### ISSUE TITLE
Missing formats

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/formats#1]
- [ ] PKCS#1: RSA Cryptography Standard
- [ ] PKCS#5: Password-based Encryption Standard
- [ ] PKCS#7: Cryptographic Message Syntax Standard
- [ ] PKCS#8: Private-Key Information Syntax Standard
- [ ] PKCS#10: Certification Request Standard
- [ ] PKCS#12: Personal Information Exchange Syntax Standard
- [ ] SPKI: X.509 Subject Public Key Info
- [ ] X.509: Public Key Infrastructure Certificate and Certificate Revocation List (CRL) Profile

Please post a comment to request additional formats

**Comment by jklong** [comment]
#3 will also require a PKCS#7 implementation so I'll start work on that as well. I've created #28 to track.

**Comment by franziskuskiefer** [comment]
Do you want to stick to the big ones or are you also interested in things like the ["TLS codec"](https://datatracker.ietf.org/doc/html/rfc8446#section-3). It's not really a standard but it's being used quite a bit by now. I have a version here https://github.com/openmls/tls-codec/

**Comment by tarcieri** [comment]
@franziskuskiefer if you so happen to be looking for another home for it I'd say that would be a great thing to have here

**Comment by jonasbb** [comment]
The new `ssh-key` crate does not seem to support ssh-keys backed by security keys, which contain the `sk` suffix in the name. There is `ecdsa_sk` which uses `sk-ecdsa-sha2-nistp256@openssh.com` in the `.pub` file and `ed25519_sk` using `sk-ssh-ed25519@openssh.com` as the identifier. 
It would be great to have support for these newer key types too, but it is not clear to me if that is currently on the todo list.

**Comment by tarcieri** [comment]
@jonasbb yes, it would be good to add support for those. Likewise it would be nice to have support for OpenSSH certificates.

I will try to get these items added to the TODO list in the README, or otherwise would merge a PR to add them.

**Comment by enri1196** [comment]
Do you think RFC3161 TimeStamp Protocol would be a good addition to the formats?

reference: https://www.rfc-editor.org/rfc/rfc3161

**Comment by carl-wallace** [comment]
I think RFC3161 would be a good addition and have thought about implementing it before but had not gotten around to it. It's referenced in some new work, for example, draft-birkholz-rats-epoch-markers.

**Comment by enri1196** [comment]
I'd like to help, can I just open a PR once I've got some basic implementation of the structures? Maybe a new folder under formats/tsp?

**Comment by tarcieri** [comment]
We'd need a crate name we actually control, although you can use that name temporarily until we pick one we do control

**Comment by leotaku** [comment]
I would potentially be interested in contributing an implementation of [RFC5544](RFC5544). Is that something the project would benefit from?

[RFC5544]: https://datatracker.ietf.org/doc/html/rfc5544.html#section-4.1

**Comment by enri1196** [comment]
Hey @leotaku I've actually created an issue for this format and I have most of the work done locally, the blocking issue for me is that I get an indefinite length error which seems to come from a BER/DER mixed encoding. #1198 I was waiting to get some feedback, but I could definitely open a PR for you to test for your self, maybe you can spot something i missed.

**Comment by leotaku** [comment]
@enri1196 That sounds great. If you open a PR or direct me to your fork I'd love to take a look.

**Comment by enri1196** [comment]
@leotaku check out PR #1258 hopefully we can get this to work

**Comment by dishmaker** [comment]
PKCS#15
ISO/IEC 7816-15
Version 2016 with amd. 2018
https://github.com/monai/node-passport/blob/master/lib/pkcs15/cryptographic_information_framework.asn1

**Comment by callumadair** [comment]
Would [RFC 6031](https://datatracker.ietf.org/doc/html/rfc6031) be a good choice for implementation?

**Comment by callumadair** [comment]
Thoughs on implementing [RFC 7906](https://datatracker.ietf.org/doc/html/rfc7906)?
